import fs from 'node:fs';
import path from 'node:path';
import {page,card,cta,arrow} from './src/shared.mjs';
export const properties=JSON.parse(fs.readFileSync('content/properties.json','utf8'));
export const reviews=JSON.parse(fs.readFileSync('content/reviews.json','utf8'));
export function write(route,html){const dest=path.join('dist',route,'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,html);}
fs.writeFileSync('dist/assets/style.css',fs.readFileSync('src/fonts.css','utf8')+'\n'+fs.readFileSync('src/style.css','utf8'));fs.copyFileSync('src/app.js','dist/assets/app.js');fs.copyFileSync('src/mortgage.js','dist/assets/mortgage.js');
write('',page({title:'Vaše nemovitost. Moje osobní péče.',description:'Petra Pokorná, certifikovaná realitní makléřka. Více než 10 let zkušeností s prodejem, koupí a pronájmem nemovitostí.',body:`
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow"><span class="line"></span>VAŠE REALITNÍ MAKLÉŘKA</p><h1>Vaše nemovitost.<br><em>Moje osobní péče.</em></h1><p class="hero-description">Provedu vás prodejem, koupí i pronájmem.<br>Srozumitelně a s jistotou.</p><div class="hero-actions"><a href="/kontakt/?tema=prodej" class="button">Chci prodat nemovitost ${arrow}</a><a href="/nemovitosti/" class="text-link">Prohlédnout nabídku ${arrow}</a></div><p class="hero-trust"><span class="trust-symbol" aria-hidden="true">⌂</span>Více než <strong>10 let</strong> v realitách</p></div><div class="hero-visual"><div class="hero-backdrop"></div><img src="/assets/petra-pokorna.png" alt="Petra Pokorná, vaše realitní makléřka" width="1000" height="1000" fetchpriority="high"><span class="signature" aria-hidden="true">Petra<br><span>Pokorná</span></span><span class="hero-visual-caption">NEMOVITOSTI S OSOBNÍM PŘÍSTUPEM</span></div></div></section>
<section class="intro-strip"><div class="container intro-inner"><div><p class="eyebrow">TĚŠÍ MĚ</p><h2>Jsem Petra. A stojím při vás.</h2></div><p>Vím, že za každou nemovitostí je příběh.<br>Ten váš si zaslouží pozornost a péči.</p><a class="text-link" href="/o-mne/">Více o mně ${arrow}</a></div></section>
<section class="section container"><div class="section-heading"><div><p class="eyebrow">AKTUÁLNĚ V NABÍDCE</p><h2>Nemovitosti s příběhem</h2></div><a class="text-link" href="/nemovitosti/">Všechny nabídky ${arrow}</a></div><div class="property-grid">${properties.map(card).join('')}</div></section>
<section class="services-section container"><div class="section-heading"><div><p class="eyebrow">OD PRVNÍ SCHŮZKY PO PŘEDÁNÍ</p><h2>Na dobré spolupráci záleží.</h2></div></div><div class="service-grid">${[['Prodej nemovitosti','Promyšlená prezentace, správné nacenění a péče o celý průběh.','prodej'],['Koupě a pronájem','Pomohu vám zorientovat se a najít řešení, které dává smysl.','koupe'],['Realitní poradenství','Jasné odpovědi na vaše otázky. Srozumitelně a bez zbytečných obav.','poradenstvi']].map(([title,text,id],i)=>`<a class="service-item" href="/sluzby/#${id}"><span class="service-number">0${i+1}</span><div><h3>${title}</h3><p>${text}</p></div>${arrow}</a>`).join('')}</div></section>
${cta()}`}));
if(fs.existsSync('src/pages.mjs')) {const {buildPages}=await import('./src/pages.mjs');await buildPages({write,properties,reviews});}
console.log('Site generated in dist/');
