export const esc = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money = n => new Intl.NumberFormat('cs-CZ',{maximumFractionDigits:0}).format(n)+' Kč';
export const arrow = '<span aria-hidden="true">↗</span>';
export const featuredArrow = '<span class="button-icon" aria-hidden="true"><svg viewBox="0 0 20 20" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" focusable="false"><path d="M5 15 15 5M5 5h10v10"/></svg></span>';
const monogram = `<path d="M10 39V9h12a10 10 0 0 1 0 20H10"/><path class="monogram-accent" d="M23 39V18h8a7 7 0 0 1 0 14h-8"/>`;
export const brand = `<svg class="brand-mark" width="46" height="46" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="square" aria-hidden="true" focusable="false">${monogram}</svg><span class="brand-wordmark"><span class="brand-name">Petra <strong>Pokorná</strong></span><span class="brand-caption">REALITNÍ MAKLÉŘKA</span></span>`;
const favicon = 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><rect width="48" height="48" rx="9" fill="#592637"/><g fill="none" stroke="#fdfbfc" stroke-width="2.4" stroke-linecap="square">${monogram.replace('class="monogram-accent"','stroke="#db9aaf"')}</g></svg>`);
const nav=[['/o-mne/','O mně'],['/nemovitosti/','Nemovitosti'],['/sluzby/','Služby'],['/poradna/','Poradna'],['/kalkulacka/','Kalkulačka']];
export function header(active){return `<header class="site-header"><div class="menu-backdrop" aria-hidden="true"></div><div class="container header-inner"><a class="brand" href="/" aria-label="Petra Pokorná – úvod">${brand}</a><button class="menu-toggle" aria-label="Otevřít navigaci" aria-expanded="false" aria-controls="navigation"><span></span><span></span></button><nav id="navigation" aria-label="Hlavní navigace"><p class="menu-intro">NEMOVITOSTI S OSOBNÍM PŘÍSTUPEM</p>${nav.map(([href,label],i)=>`<a class="nav-link" href="${href}" ${active===href?'aria-current="page"':''}><span class="nav-index" aria-hidden="true">0${i+1}</span><span>${label}</span><span class="nav-arrow" aria-hidden="true">↗</span></a>`).join('')}<div class="menu-contact"><span>Ráda si na vás udělám čas</span><a href="tel:+420602588332">+420 602 588 332</a></div><a class="button button-small button-featured nav-cta" href="/kontakt/" ${active==='/kontakt/'?'aria-current="page"':''}><span class="button-label">Domluvit konzultaci</span>${featuredArrow}</a></nav></div></header>`;}
export function cta(title='Pojďme probrat vaše plány.'){return `<section class="contact-band"><div class="container contact-band-inner"><div><p class="eyebrow">PRVNÍ KROK ZAČÍNÁ ROZHOVOREM</p><h2>${title}</h2><p>Jsem tu pro vaše otázky. Společně najdeme správnou cestu.</p></div><a href="/kontakt/" class="button button-white">Domluvit konzultaci ${arrow}</a></div></section>`;}
export function footer(){return `<footer class="site-footer"><div class="container"><div class="footer-top"><a href="/" class="brand">${brand}</a><p>Osobní přístup. Férové jednání.<br>Péče v každém kroku.</p><div class="footer-contact"><a href="tel:+420602588332">+420 602 588 332</a><a href="mailto:petra.pokorna@bidli.cz">petra.pokorna@bidli.cz</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Petra Pokorná</span><div><a href="/kontakt/">Kontakt</a><a href="/soukromi/">Soukromí</a><a href="https://www.bidli.cz/specialista/petra-pokorna/12747" target="_blank" rel="noopener noreferrer">Profil BIDLI ${arrow}</a></div><span>S péčí o váš domov.</span></div></div></footer>`;}
export function page({title,description,active='',body,script='',className=''}){return `<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#bc5174"><title>${esc(title)} | Petra Pokorná</title><meta name="description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:locale" content="cs_CZ"><meta property="og:title" content="${esc(title)} | Petra Pokorná"><meta property="og:description" content="${esc(description)}"><link rel="icon" type="image/svg+xml" href="${favicon}"><link rel="stylesheet" href="/assets/style.css"><script type="module" src="/assets/app.js"></script>${script}</head><body class="${className}"><a class="skip-link" href="#main">Přejít k obsahu</a>${header(active)}<main id="main">${body}</main>${footer()}</body></html>`;}
export function card(p){return `<article class="property-card" data-property data-type="${p.type}" data-city="${esc(p.location)}" data-price="${p.price}"><a class="property-photo" href="/nemovitosti/${p.slug}/" tabindex="-1" aria-hidden="true"><img src="${p.photos[0]}" alt="${esc(p.title)}" width="800" height="600" loading="lazy"><span class="badge">Prodej</span><span class="photo-count">${p.photos.length} fotografií</span></a><div class="property-content"><p class="property-location">${esc(p.location)}</p><h3><a href="/nemovitosti/${p.slug}/">${esc(p.title)}</a></h3><p class="property-meta">${esc(p.layout)} <span>·</span> ${p.area} m²</p><div class="property-bottom"><strong>${money(p.price)}</strong><a href="/nemovitosti/${p.slug}/" class="circle-link" aria-label="Detail: ${esc(p.title)}">${arrow}</a></div></div></article>`;}
export function breadcrumb(label,parents=[]){return `<nav class="breadcrumb container" aria-label="Drobečková navigace"><a href="/">Úvod</a>${parents.map(([href,text])=>`<span>/</span><a href="${href}">${esc(text)}</a>`).join('')}<span>/</span><span aria-current="page">${esc(label)}</span></nav>`;}
